pipeline {
    agent any

    stages {
        stage('Install and Setup') {
            steps {
                sh 'apt-get update && apt-get install -y python3 python3-venv'
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install --upgrade pip pytest'
            }
        }

        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/wlcamargo/jenkins.git']]])
            }
        }

        stage('Build') {
            steps {
                sh '. venv/bin/activate && python3 test/ops.py'
            }
        }

        stage('Test') {
            steps {
                sh '. venv/bin/activate && python3 -m pytest'
            }
        }
    }

    post {
        always {
            sh 'deactivate || true'
        }
    }
}
